name: OSMnxPyrLab
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - affine=2.3.1=pyhd8ed1ab_0
  - anyio=3.6.1=pyhd8ed1ab_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - astroid=2.12.12=py310hff52083_1
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - black=22.10.0=py310hff52083_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.1=h83bc5f7_3
  - boost-cpp=1.78.0=h75c5d50_1
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py310h255011f_0
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310hff52083_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.5=py310hbf28c38_0
  - cryptography=38.0.1=py310h597c629_0
  - curl=7.85.0=h7bff187_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cykhash=2.0.0=py310hd8f1fbe_1
  - cython=0.29.32=py310hd8f1fbe_0
  - debugpy=1.6.3=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.0.4=pyhd8ed1ab_0
  - executing=1.1.0=pyhd8ed1ab_0
  - expat=2.4.9=h27087fc_0
  - fiona=1.8.21=py310h60a68a4_2
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.37.4=py310h5764c6d_0
  - freetype=2.12.1=hca18f0e_0
  - freexl=1.0.6=h166bdaf_1
  - gdal=3.5.2=py310hb7951cf_1
  - geopandas=0.11.1=pyhd8ed1ab_0
  - geopandas-base=0.11.1=pyha770c72_0
  - geos=3.11.0=h27087fc_0
  - geotiff=1.7.1=h4fc65e6_3
  - gettext=0.19.8.1=h27087fc_1009
  - giflib=5.2.1=h36c2ea0_2
  - hdf4=4.2.15=h9772cbc_4
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.16.0=pyh210e3f2_0
  - ipython=8.5.0=pyh41d4057_1
  - ipython_genutils=0.2.0=py_1
  - isort=5.10.1=pyhd8ed1ab_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json-c=0.16=hc379101_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hff52083_0
  - jupyter_server=1.19.1=pyhd8ed1ab_0
  - jupyterlab=3.4.8=pyhd8ed1ab_0
  - jupyterlab_code_formatter=1.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.2=pyhd8ed1ab_0
  - kealib=1.4.15=ha7026e8_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lazy-object-proxy=1.8.0=py310h5764c6d_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.85.0=h7bff187_0
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgdal=3.5.2=hc23bfc3_1
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.74.0=h7a41b64_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.17=h166bdaf_0
  - libkml=1.3.0=h37653c0_1015
  - liblapack=3.9.0=16_linux64_openblas
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=hd77ab85_0
  - librttopo=1.1.0=hf730bdb_11
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=hd36657c_19
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h55922b4_4
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.2=h4c7fe37_1
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.12=h166bdaf_4
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib-base=3.6.0=py310h8d5ebf3_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mccabe=0.7.0=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=0.4.3=py310hff52083_5
  - nbclassic=0.4.4=pyhd8ed1ab_0
  - nbclient=0.6.8=pyhd8ed1ab_0
  - nbconvert=7.1.0=pyhd8ed1ab_0
  - nbconvert-core=7.1.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.1.0=pyhd8ed1ab_0
  - nbformat=5.6.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.8.7=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.3=py310h53a5b5f_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1s=h166bdaf_0
  - osmnx=1.2.2=pyhd8ed1ab_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.0=py310h769672d_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.10.1=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=hc3806b6_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310hbd86126_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.5.2=pyhd8ed1ab_1
  - pluggy=1.0.0=pyhd8ed1ab_5
  - poppler=22.04.0=h0733791_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.5=hfdbbde3_0
  - proj=9.0.1=h93bde94_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py310h5764c6d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygeos=0.13=py310h5e49deb_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pylint=2.15.5=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.4.0=py310hf94497c_0
  - pyrobuf=0.9.3=py310hd8f1fbe_4
  - pyrosm=0.6.1=py310hd8f1fbe_1
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.2.0=pyhd8ed1ab_2
  - python=3.10.6=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-rapidjson=1.6=py310hd8f1fbe_0
  - python_abi=3.10=2_cp310
  - pytz=2022.4=pyhd8ed1ab_0
  - pyzmq=24.0.1=py310h330234f_0
  - rasterio=1.3.2=py310h1bedc6d_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rtree=1.0.0=py310hbdcdc62_1
  - scikit-learn=1.1.2=py310h0c3af53_0
  - scipy=1.9.1=py310hdfbd76f_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.4.1=pyhd8ed1ab_0
  - shapely=1.8.4=py310h5e49deb_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.4=h4ff8645_0
  - stack_data=0.5.1=pyhd8ed1ab_0
  - terminado=0.16.0=pyh41d4057_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.11.3=h1e4a385_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.11.6=pyha770c72_0
  - tornado=6.2=py310h5764c6d_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzcode=2022d=h166bdaf_0
  - tzdata=2022d=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - wrapt=1.14.1=py310h5764c6d_1
  - xerces-c=3.2.3=h55805fa_5
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2022.9.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_4
  - zstd=1.5.2=h6239696_4
prefix: /home/carlsonb/miniconda3/envs/OSMnxPyrLab
